name = "CenterOfGravity"
uuid = "d98d927a-eebc-4e2e-bfd8-b8854602986e"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.1"

[deps]
CartesianBoxes = "f894539e-422c-4c16-819a-0e1d0163d378"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TypeUtils = "ca91d8e0-3195-446d-9999-6c164cca1bdd"

[compat]
CartesianBoxes = "0.3"
TypeUtils = "0.2, 0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
